app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@AppBundle/Resources/config/api-routing.yml"
    type:     rest
    prefix:   /api