services:
    app.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getManager]
        public: false

    app.files:
        class: AppBundle\Services\Files
        arguments:
            - "%kernel.root_dir%"