services:
    app.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getManager]
        public: true

    app.files:
        class: AppBundle\Services\Files
        arguments:
            - "%kernel.root_dir%"
            
    app.image.manager:
        class: AppBundle\Entity\EntityManager\ImageManager
        arguments:
            - "@app.entity_manager"
            