AppBundle\Entity\Image:
    type:  entity
    table: image
    repositoryClass: AppBundle\Entity\Repository\ImageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        link:
            type: string
            length: 255
            column: link
        dateCreate:
            type: datetime
            column: date_create
        dateUpdate:
            type: datetime
            column: date_update

    manyToMany:
        tags:
            targetEntity: AppBundle\Entity\Tag
            joinTable:
                name: images_to_tags
                joinColumns:
                    image_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [setDateCreateValue, setDateUpdateValue]
        preUpdate: [setDateUpdateValue]