AppBundle\Entity\Image:
    type:  entity
    table: image
    repositoryClass: AppBundle\Entity\Repository\ImageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        link:
            type: string
            length: 255
            column: link
        dateCreate:
            type: datetime
            column: date_create
        dateUpdate:
            type: datetime
            column: date_update

    lifecycleCallbacks:
        prePersist: [setDateCreateValue, setDateUpdateValue]
        preUpdate: [setDateUpdateValue]